name: Detect TODOs in PRs

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  pull-requests: write
  issues: write

jobs:
  hello_world:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello World
        run: echo "Hello, World!"

  detect_todos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the PR code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

        - name: Generate Diff
        run: |
          BASE=${{ github.event.pull_request.base.ref }}
          HEAD=${{ github.event.pull_request.head.ref }}
          git diff origin/$BASE..origin/$HEAD -- . ':!path/to/file_to_exclude.js' > diff.txt || true

      - name: Get the list of TODOs with File and Line Numbers
        id: find_todos
        run: |
          grep -nE '^\+.*// TODO:' diff.txt > todos_with_metadata.txt || true

          if [ -s todos_with_metadata.txt ]; then
            echo "Found TODOs with metadata:"
            cat todos_with_metadata.txt

            echo "todos=true" >> $GITHUB_ENV
          else
            echo "todos=false" >> $GITHUB_ENV
          fi

      - name: Comment on Each TODO with File and Line Info
        if: ${{ env.todos == 'true' }}
        run: |
          while IFS= read -r todo; do
            if [[ "$todo" =~ ^([0-9]+):(\+.*)(// TODO:.*)$ ]]; then
              line_number="${BASH_REMATCH[1]}"
              content="${BASH_REMATCH[3]}"
              echo "TODO found on line $line_number: $content"

              file=$(grep -B 100 "$content" diff.txt | head -n 1 | sed 's/^diff --git a\///g' | awk '{print $1}')
              
              gh pr comment ${{ github.event.pull_request.number }} --body "⚠️ **New TODO detected**:
              **File:** \`${file}\`  
              **Line:** \`${line_number}\`  
              \`\`\`
              $content
              \`\`\`"
            fi
          done < todos_with_metadata.txt
  