name: Detect TODOs in PRs

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  pull-requests: write
  issues: write

jobs:
  hello_world:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello World
        run: echo "Hello, World!"

  detect_todos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the PR code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history to avoid shallow clone issues
        # with:
        #   ref: ${{ github.event.pull_request.head.ref }}
        #   repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Show branch history
        run: |
          git log --oneline origin/main || echo "No main branch history."
          git log --oneline origin/dev || echo "No dev branch history."

      - name: Fetch Branches Properly
        run: |
          git fetch origin ${{ github.event.pull_request.base.ref }}
          git fetch origin ${{ github.event.pull_request.head.ref }}

      - name: Generate Diff
        run: |
          DIFF=$(git diff origin/${{ github.event.pull_request.base.ref }}..origin/${{ github.event.pull_request.head.ref }} || true)
          echo "$DIFF"

      - name: Get the list of TODOs from the diff
        id: find_todos
        run: |
          BASE=${{ github.event.pull_request.base.ref }}
          HEAD=${{ github.event.pull_request.head.ref }}
          DIFF=$(git diff origin/$BASE..origin/$HEAD || true)
          echo "$DIFF"
          TODOS=$(echo "$DIFF" | grep -E '^\+.*// TODO:' || true)
          if [ -n "$TODOS" ]; then
            echo "Encoded TODOs:"
            echo "$TODOS" | base64 > todos.txt
            cat todos.txt
            echo "todos=$(cat todos.txt)" >> $GITHUB_ENV
          fi

      - name: Debug PR Number
        run: |
          echo "PR Number: ${{ github.event.pull_request.number }}"

      - name: Debug TODOs Output
        run: |
          echo "TODOs: ${{ env.todos }}"
          if [ -z "${{ env.todos }}" ]; then
            echo "No TODOs detected."
          fi

      - name: Comment on Each TODO if Found
        if: ${{ env.todos != '' }}
        run: |
          while IFS= read -r todo; do
            if [ -n "$todo" ]; then
              echo "Commenting TODO: $todo"
              gh pr comment ${{ github.event.pull_request.number }} --body "⚠️ **New TODO detected in this PR:** \n```\n$todo\n```"
            fi
          done < todos.txt
