name: Detect TODOs in PRs

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  pull-requests: write
  issues: write

jobs:
  hello_world:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello World
        run: echo "Hello, World!"

  detect_todos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the PR code
        uses: actions/checkout@v3
        # with:
        #   ref: ${{ github.event.pull_request.head.ref }}
        #   repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Show branch history
        run: |
          git log --oneline origin/main
          git log --oneline origin/dev

      - name: Fetch Branches Properly
        run: |
          git fetch origin ${{ github.event.pull_request.base.ref }}
          git fetch origin ${{ github.event.pull_request.head.ref }}

      - name: Generate Diff
        run: |
          DIFF=$(git diff origin/${{ github.event.pull_request.base.ref }}..origin/${{ github.event.pull_request.head.ref }} || true)
          echo "$DIFF"

      - name: Get the list of TODOs from the diff
        id: find_todos
        run: |
          git fetch origin ${{ github.event.pull_request.base.ref }} ${{ github.event.pull_request.head.ref }}
          BASE_BRANCH="origin/${{ github.event.pull_request.base.ref }}"
          HEAD_BRANCH="origin/${{ github.event.pull_request.head.ref }}"

          # Check for common ancestor
          if git merge-base --is-ancestor $BASE_BRANCH $HEAD_BRANCH; then
            DIFF=$(git diff $BASE_BRANCH...$HEAD_BRANCH)
            TODOS=$(echo "$DIFF" | grep -E '^\+.*TODO:' || true)
            if [ -n "$TODOS" ]; then
              echo "todos=$TODOS" >> $GITHUB_ENV
            fi
          else
            echo "No common ancestor found between $BASE_BRANCH and $HEAD_BRANCH."
          fi

      - name: Debug PR Number
        run: |
          echo "PR Number: ${{ github.event.pull_request.number }}"

      - name: Debug TODOs Output
        run: |
          echo "TODOs: ${{ env.todos }}"
          if [ -z "${{ env.todos }}" ]; then
            echo "No TODOs detected."
          fi

      - name: Comment on the PR if TODOs are found
        if: ${{ env.todos != '' }}
        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ⚠️ **New TODOs detected in this PR:**
            ```
            ${{ env.todos }}
            ```
