name: Detect TODOs in PRs

on:
  pull_request_target:
    types: [opened, synchronize]

permissions:
  pull-requests: write
  issues: write

jobs:
  detect_todos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the PR code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Get the list of TODOs from the diff
        id: find_todos
        run: |
          git fetch origin ${{ github.event.pull_request.base.ref }} ${{ github.event.pull_request.head.ref }}
          DIFF=$(git diff origin/${{ github.event.pull_request.base.ref }}...origin/${{ github.event.pull_request.head.ref }})

          TODOS=$(echo "$DIFF" | grep -E '^\+.*// TODO:' || true)

          if [ -n "$TODOS" ]; then
            echo "::set-output name=todos::$TODOS"
          fi

      - name: Debug PR Number
        run: echo "PR Number: ${{ github.event.pull_request.number }}"

      - name: Debug TODOs Output
        run: |
          echo "TODOs: ${{ steps.find_todos.outputs.todos }}"

      - name: Comment on the PR if TODOs are found
        if: steps.find_todos.outputs.todos != ''
        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ⚠️ **New TODOs detected in this PR:**

            ```
            ${{ steps.find_todos.outputs.todos }}
            ```
