name: Detect TODOs in PRs

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  pull-requests: write
  issues: write

jobs:
  detect_todos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the PR code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Fetch Branches Properly
        run: |
          git fetch origin ${{ github.event.pull_request.base.ref }}
          git fetch origin ${{ github.event.pull_request.head.ref }}

      - name: Generate Diff
        run: |
          BASE=${{ github.event.pull_request.base.ref }}
          HEAD=${{ github.event.pull_request.head.ref }}
          git diff origin/$BASE..origin/$HEAD -- . ':!path/to/file_to_exclude.js' > diff.txt || true

      - name: Get the list of TODOs with File and Line Numbers
        id: find_todos
        run: |
          awk '/^diff --git a\// {file = $3; sub(/^a\//, "", file)} 
               /^[+].*\/\/ TODO:/ {print file ":" NR ":" $0}' diff.txt > todos_with_metadata.txt || true

          if [ -s todos_with_metadata.txt ]; then
            echo "Found TODOs with metadata:"
            cat todos_with_metadata.txt

            echo "todos=true" >> $GITHUB_ENV
          else
            echo "todos=false" >> $GITHUB_ENV
          fi

      - name: Comment on Each TODO with File and Line Info
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ env.todos == 'true' }}
        run: |
          while IFS= read -r todo; do
            # Split the todo entry into file, line number, and content
            file=$(echo "$todo" | cut -d ':' -f 1)
            line_number=$(echo "$todo" | cut -d ':' -f 2)
            content=$(echo "$todo" | cut -d ':' -f 3-)

            echo "TODO found in $file on line $line_number: $content"

            # Post the comment to the PR
            gh pr comment ${{ github.event.pull_request.number }} --body "⚠️ **New TODO detected**:
            **File:** \`${file}\`  
            **Line:** \`${line_number}\`  
            \`\`\`
            $content
            \`\`\`"
          done < todos_with_metadata.txt
