name: Detect TODOs in PRs

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  pull-requests: write
  issues: write

jobs:
  hello_world:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello World
        run: echo "Hello, World!"

  detect_todos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the PR code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Show branch history
        run: |
          git log --oneline origin/main || echo "No main branch history."
          git log --oneline origin/dev || echo "No dev branch history."

      - name: Fetch Branches Properly
        run: |
          git fetch origin ${{ github.event.pull_request.base.ref }}
          git fetch origin ${{ github.event.pull_request.head.ref }}

      - name: Generate Diff and Extract TODOs
        id: find_todos
        run: |
          BASE=${{ github.event.pull_request.base.ref }}
          HEAD=${{ github.event.pull_request.head.ref }}

          echo "Generating diff between $BASE and $HEAD..."
          DIFF=$(git diff origin/$BASE..origin/$HEAD -- . ':!.github/workflows/detect-todos.yml' || true)

          echo "Extracting TODOs..."
          TODOS=$(echo "$DIFF" | grep -E '^\+.*// TODO:' || true)

          if [ -n "$TODOS" ]; then
            echo "$TODOS" > todos.txt
            echo "todos=true" >> $GITHUB_ENV
          else
            echo "No TODOs found."
          fi

          grep -nE '^\+.*// TODO:' diff.txt > todos_with_metadata.txt || true

          if [ -s todos_with_metadata.txt ]; then
            echo "Found TODOs with metadata:"
            cat todos_with_metadata.txt

            echo "todos=true" >> $GITHUB_ENV
          else
            echo "todos=false" >> $GITHUB_ENV
          fi

      - name: Debug PR Number
        run: |
          echo "PR Number: ${{ github.event.pull_request.number }}"

      - name: Debug TODOs Output
        run: |
          echo "Content of todos.txt:"
          cat todos.txt || echo "No TODOs detected."

      # - name: Comment on Each TODO if Found
      #   if: ${{ env.todos != '' }}
      #   env:
      #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     while IFS= read -r todo; do
      #       if [ -n "$todo" ]; then
      #         echo "Commenting TODO: $todo"
      #         gh pr comment ${{ github.event.pull_request.number }} \
      #           --body $'⚠️ **New TODO detected in this PR:**\n```\n'"$todo"$'\n```'
      #       fi
      #     done < todos.txt
      - name: Comment on Each TODO with File and Line Info
        if: ${{ env.todos == 'true' }}
        run: |
          while IFS= read -r todo; do
            if [[ "$todo" =~ ^([0-9]+):(\+.*)(// TODO:.*)$ ]]; then
              line_number="${BASH_REMATCH[1]}"
              content="${BASH_REMATCH[3]}"
              echo "TODO found on line $line_number: $content"

              file=$(grep -B 100 "$content" diff.txt | head -n 1 | sed 's/^diff --git a\///g' | awk '{print $1}')
              
              gh pr comment ${{ github.event.pull_request.number }} --body "⚠️ **New TODO detected**:**File:** \`${file}\`  **Line:** \`${line_number}\`  \`\`\`$content\`\`\`" fi done < todos_with_metadata.txt
