name: Detect TODOs in PRs

on:
  pull_request_target:
    types: [opened, synchronize]

permissions:
  pull-requests: write
  issues: write

jobs:
  detect_todos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the PR code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      # - name: Get the list of TODOs from the diff
      #   id: find_todos
      #   run: |
      #     git fetch origin ${{ github.event.pull_request.base.ref }} ${{ github.event.pull_request.head.ref }}
      #     DIFF=$(git diff origin/${{ github.event.pull_request.base.ref }}...origin/${{ github.event.pull_request.head.ref }})
      #     TODOS=$(echo "$DIFF" | grep -E '^\+.*TODO:' || true)
      #     if [ -n "$TODOS" ]; then
      #       echo "todos=$TODOS" >> $GITHUB_ENV
      #     fi

      - name: Get the list of TODOs from the diff
        id: find_todos
        run: |
          echo "Fetching base and head refs..."
          git fetch origin ${{ github.event.pull_request.base.ref }} ${{ github.event.pull_request.head.ref }}

          echo "Generating diff between base and head:"
          DIFF=$(git diff origin/${{ github.event.pull_request.base.ref }}...origin/${{ github.event.pull_request.head.ref }})
          echo "$DIFF" # Print the diff to confirm its content

          echo "Searching for TODOs in the diff..."
          TODOS=$(echo "$DIFF" | grep -E '^\+.*// TODO:' || true)

          if [ -n "$TODOS" ]; then
            echo "Found TODOs:"
            echo "$TODOS" # Log found TODOs for debugging
            echo "todos=$TODOS" >> $GITHUB_ENV
          else
            echo "No TODOs found."
          fi

      - name: Debug PR Number
        run: |
          echo "PR Number: ${{ github.event.pull_request.number }}"

      - name: Debug TODOs Output
        run: |
          echo "TODOs: ${{ env.todos }}"
          if [ -z "${{ env.todos }}" ]; then
            echo "No TODOs detected."
          fi

      - name: Comment on the PR if TODOs are found
        if: ${{ env.todos != '' }}
        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ⚠️ **New TODOs detected in this PR:**
            ```
            ${{ env.todos }}
            ```
