name: Detect TODOs in PRs

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  pull-requests: write
  issues: write

jobs:
  hello_world:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello World
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: echo "Hello, World!"
