name: Detect TODOs in PRs

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  pull-requests: write
  issues: write

jobs:
  hello_world:
    runs-on: ubuntu-latest
    # Runs only if 'run-sanity' label is applied
    if: contains(github.event.pull_request.labels.*.name, 'run-sanity')
    steps:
      - name: Print Hello World
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: echo "Hello, World!"
